// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

let SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Force HTTPS in production (browser) if URL is HTTP
if (typeof window !== 'undefined' && SUPABASE_URL && SUPABASE_URL.startsWith('http://')) {
  console.warn('⚠️ Supabase URL is using HTTP. Converting to HTTPS for secure connections.');
  SUPABASE_URL = SUPABASE_URL.replace('http://', 'https://');
}

// Diagnostic logging (remove in production if needed)
if (typeof window !== 'undefined') {
  console.log('Supabase Configuration Check:');
  console.log('SUPABASE_URL:', SUPABASE_URL ? `${SUPABASE_URL.substring(0, 50)}...` : 'MISSING');
  console.log('SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.substring(0, 20)}...` : 'MISSING');
  
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error('❌ Supabase environment variables are missing!');
    console.error('Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set in your build environment.');
  } else {
    if (SUPABASE_URL.startsWith('https://')) {
      console.log('✅ Supabase environment variables are loaded (HTTPS)');
    } else {
      console.warn('⚠️ Supabase URL should use HTTPS in production');
    }
  }
}

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. ' +
    'Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set in your build environment.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});